### ISSUE TITLE
Not favorites

### ISSUE THREAD

**Issue by jrspowers** [johanfrick/custom-sonos-card#26] opened 2022-02-26 12:55 UTC
hello I don't get favorites in the sonos card after updating to the latest version ha as restarted but no difference ?![image](https://user-images.githubusercontent.com/60328474/155844141-998e872c-b922-4b0d-a837-dd462271f1d9.jpeg)

**Comment by johanfrick** [comment] 2022-02-26 21:27
Duplicate of #25 . Please post your findings there.

**Closed by johanfrick** 2022-02-26 21:27 UTC
Labels: bug
