### ISSUE TITLE
favorites not available when a any of the specified entites are not online

### ISSUE THREAD

**Issue by usingapc** [johanfrick/custom-sonos-card#143] opened 2023-06-20 18:59 UTC
I've played around with the last v6, v6.1, and v6.2

It seems that if I specified the entities(Speakers) I wanted to show(mainly so that I could put them in a specific order) and any one of those entities is offline, none of the speakers show any of my favorite music channels or media at all in the favorites tab.  If I remove the entity that is offline from the list the favorite section works and shows my favorites again.

**Comment by johanfrick** [comment] 2023-06-20 20:45
I fail to reproduce this. Can you please share your config YAML?

**Comment by gdgib** [comment] 2023-06-21 01:01
I think there's a good chance this has the same root cause as #140 , fixed I think I fixed in #144.  I say that because the underlying cause was a lack of `source_list` attributes on the non-TV sonos players, which would of course also happen if the device is offline.

**Comment by johanfrick** [comment] 2023-06-21 17:19
Great, I've released #144 now so closing this issue then

**Closed by johanfrick** 2023-06-21 17:19 UTC
Labels: bug
